enum EstadoAtualLogin{AUTHENTICATED, UNAUTENTICATED, AUTHENTICATING, APP_START}

enum StatusAgendamento{AGENDADO, PENDENTE, CANCELADO, REALIZADO, NAO_REALIZADO}

enum Routes{PRODUCAO_VIEW, EVENTO_VIEW, LOGIN_VIEW}

enum StatusCadastroEvento{OK, ERRO, CADASTRANDO}